# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YourCartoon' do
    pod 'MarqueeLabel', '~> 2.3'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'AFNetworking', '~> 2.5.4'
    pod 'Google-Mobile-Ads-SDK'
    pod 'mopub-ios-sdk', '~> 4.0'
end

